"""empty message

Revision ID: 5d69bb931158
Revises: 
Create Date: 2020-06-22 16:36:03.277764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d69bb931158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_info',
    sa.Column('movieid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('director_actor', sa.String(length=300), nullable=False),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Integer(), nullable=True),
    sa.Column('introduce', sa.String(length=200), nullable=True),
    sa.Column('poster', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('movieid', name=op.f('pk_movie_info'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=400), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movie_info.movieid'], name=op.f('fk_comments_movieid_movie_info')),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.userid'], name=op.f('fk_comments_user_id_user_info')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_time'), 'comments', ['time'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_time'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('movie_info')
    # ### end Alembic commands ###
