"""增加一行like

Revision ID: 80d632c8c19e
Revises: 5d69bb931158
Create Date: 2020-06-29 09:59:47.852763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d632c8c19e'
down_revision = '5d69bb931158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_info', sa.Column('like_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_info', 'like_num')
    # ### end Alembic commands ###
